-- AlterTable
ALTER TABLE "Author" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Publisher" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "RentalLog" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
